# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 11:43
from __future__ import unicode_literals

import articles.models
from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_auto_20170505_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='CbArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('image', models.ImageField(default='article_image.png', upload_to=articles.models.upload_article_image)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_article', to='main.CbCategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_articles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cb_article',
            },
        ),
        migrations.CreateModel(
            name='CbArticleComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_comments', to='articles.CbArticle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_article_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cb_article_comment',
            },
        ),
        migrations.CreateModel(
            name='CbArticleCommentLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_comment_likes', to='articles.CbArticleComment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_article_comment_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cb_article_comment_like',
            },
        ),
        migrations.CreateModel(
            name='CbArticleCommentReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_replies', to='articles.CbArticleComment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_article_cr', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cb_article_comment_reply',
            },
        ),
        migrations.CreateModel(
            name='CbArticleCommentReplyLikes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment_reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_cr_likes', to='articles.CbArticleCommentReply')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_article_cr_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cb_article_comment_reply_like',
            },
        ),
        migrations.CreateModel(
            name='CbArticleLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_likes', to='articles.CbArticle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_article_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cb_article_like',
            },
        ),
        migrations.CreateModel(
            name='CbArticleTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_tags', to='articles.CbArticle')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.CbTag')),
            ],
            options={
                'db_table': 'cb_article_tags',
            },
        ),
    ]
