# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-24 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_cbarticle_is_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='cbarticlecommentreply',
            name='content',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
