version: '3.8'
services:
  web:
    build: .
    command: gunicorn cibansa.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app:cached
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-cibansa}
      POSTGRES_USER: ${POSTGRES_USER:-cibansa}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-cibansa}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
