# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-24 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20170523_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='cbuserprofile',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
