# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-06 04:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_cbuserprofile_is_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cbuserprofile',
            name='country',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
