# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-08 09:40
from __future__ import unicode_literals

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20170606_0412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cbuserprofile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=accounts.models.photo_upload_path),
        ),
    ]
