# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 19:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20170505_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cbtopictags',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_tags', to='main.CbTopic'),
        ),
    ]
