# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 08:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20170506_0719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cbtopic',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_topics', to='main.CbCategory'),
        ),
    ]
