# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 21:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20170506_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cbquestion',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_questions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cbquestion',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_questions', to='main.CbTopic'),
        ),
    ]
