# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 21:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20170507_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cbanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_answers', to='main.CbQuestion'),
        ),
    ]
