# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 06:43
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20170508_0640'),
    ]

    operations = [
        migrations.AddField(
            model_name='cbtopic',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, default='t', editable=False, max_length=200, populate_from='title'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cbquestion',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, max_length=200, populate_from='title'),
        ),
    ]
