# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 06:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20170508_0643'),
    ]

    operations = [
        migrations.AddField(
            model_name='cbquestion',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='category_questions', to='main.CbCategory'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cbanswerlike',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_likes', to='main.CbAnswer'),
        ),
        migrations.AlterField(
            model_name='cbanswerreply',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_replies', to='main.CbAnswer'),
        ),
        migrations.AlterField(
            model_name='cbanswerreplylike',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_reply_likes', to='main.CbAnswer'),
        ),
        migrations.AlterField(
            model_name='cbcategory',
            name='name',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
