# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 07:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20170509_0608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cbquestion',
            name='category',
        ),
    ]
