# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 08:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_cbquestion_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='cbquestion',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='category_questions', to='main.CbCategory'),
            preserve_default=False,
        ),
    ]
