# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 04:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_cbquestion_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cbanswer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answer', to=settings.AUTH_USER_MODEL),
        ),
    ]
