# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-13 10:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0014_auto_20170511_0447'),
    ]

    operations = [
        migrations.AddField(
            model_name='cbanswerreplylike',
            name='answer_reply',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='answer_reply_likes', to='main.CbAnswerReply'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='cbanswerlike',
            unique_together=set([('answer', 'user')]),
        ),
        migrations.RemoveField(
            model_name='cbanswerreplylike',
            name='answer',
        ),
        migrations.AlterUniqueTogether(
            name='cbanswerreplylike',
            unique_together=set([('answer_reply', 'user')]),
        ),
    ]
