# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-20 12:31
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20170513_1118'),
    ]

    operations = [
        migrations.CreateModel(
            name='CbCategoryTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cb_category_tags',
            },
        ),
        migrations.AddField(
            model_name='cbcategory',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cbtopic',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='cbcategory',
            name='description',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='cbcategory',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='cbcategory',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, max_length=200, populate_from='name', unique=True),
        ),
        migrations.AlterField(
            model_name='cbquestion',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, max_length=200, populate_from='title', unique=True),
        ),
        migrations.AlterField(
            model_name='cbtag',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='cbtag',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, max_length=200, populate_from='name', unique=True),
        ),
        migrations.AlterField(
            model_name='cbtopic',
            name='description',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='cbtopic',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, max_length=200, populate_from='title', unique=True),
        ),
        migrations.AlterField(
            model_name='cbtopic',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name='cbcategorytags',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_tags', to='main.CbCategory'),
        ),
        migrations.AddField(
            model_name='cbcategorytags',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.CbTag'),
        ),
    ]
