# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-01 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20170520_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='cbquestion',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
