# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-26 08:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20171226_1420'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cbcourses',
            table='cb_courses',
        ),
    ]
